/* ── Real-time SSE hook ───────────────────────────────────────────
   Connects to /api/events and invalidates React Query caches
   whenever the server broadcasts a data-change event.
   Query keys match the URL-based keys generated by @workspace/api-client-react.
──────────────────────────────────────────────────────────────── */

import { useEffect, useRef } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { useCart, type CartItem } from "@/contexts/cart-context";

const BASE_URL = import.meta.env.BASE_URL?.replace(/\/$/, "") ?? "";

export type SseEventType =
  | "connected"
  | "stock_updated"
  | "bill_created"
  | "product_created"
  | "product_updated"
  | "low_stock_alert"
  | "cart_updated"
  | "held_bills_updated";

/** Notify plain-fetch pages (Billing, Customers) that server data changed.
 *  Those pages don't use React Query, so cache invalidation can't reach them;
 *  they listen for these window events and re-fetch. */
function notify(name: "addison:bills-changed" | "addison:suppliers-changed") {
  if (typeof window !== "undefined") window.dispatchEvent(new Event(name));
}

/** Invalidate all dashboard-related queries */
function invalidateDashboard(qc: ReturnType<typeof useQueryClient>) {
  qc.invalidateQueries({ queryKey: ["/api/dashboard/summary"] });
  qc.invalidateQueries({ queryKey: ["/api/dashboard/today-activity"] });
  qc.invalidateQueries({ queryKey: ["/api/dashboard/low-stock"] });
  qc.invalidateQueries({ queryKey: ["/api/dashboard/categories"] });
}

/**
 * Invalidate ALL product-related queries:
 * - /api/products          (list page)
 * - /api/products/sku/:sku (ProductDetail page — was missing before!)
 * - /api/products/:id      (any individual product fetch)
 * - /api/stock-logs        (activity log)
 */
function invalidateAllProducts(qc: ReturnType<typeof useQueryClient>) {
  qc.invalidateQueries({
    predicate: (query) => {
      const key = query.queryKey[0];
      return typeof key === "string" && key.startsWith("/api/products");
    },
  });
  qc.invalidateQueries({ queryKey: ["/api/stock-logs"] });
}

export function useRealtime() {
  const qc             = useQueryClient();
  const ref            = useRef<EventSource | null>(null);
  const { syncFromServer } = useCart();
  // Keep syncFromServer in a ref so the SSE effect never needs to reconnect when it changes
  const syncRef = useRef(syncFromServer);
  useEffect(() => { syncRef.current = syncFromServer; }, [syncFromServer]);

  useEffect(() => {
    let retryTimer: ReturnType<typeof setTimeout>;
    let retryDelay = 2000;

    function connect() {
      const es = new EventSource(`${BASE_URL}/api/events`);
      ref.current = es;

      es.addEventListener("connected", () => {
        retryDelay = 2000;          // reset back-off on successful connect
      });

      /* ── stock changed ── */
      es.addEventListener("stock_updated", (e) => {
        const d = JSON.parse(e.data) as {
          productName: string;
          productSku:  string;
          type:        "IN" | "OUT" | "ADJUSTMENT";
          quantity:    number;
          newStock:    number;
        };

        // Invalidate product list + the specific SKU query (ProductDetail page)
        invalidateAllProducts(qc);
        invalidateDashboard(qc);

        if (d.type === "IN") {
          toast.info(`📦 Stock IN — ${d.productName} +${d.quantity} (total: ${d.newStock})`, {
            duration: 3000,
          });
        }
      });

      /* ── bill checked out ── */
      es.addEventListener("bill_created", (e) => {
        const d = JSON.parse(e.data) as {
          billId:      string;
          totalAmount: number;
          itemsCount:  number;
          paymentMode: string;
        };
        // Bill deducts stock from multiple products — invalidate all product queries
        invalidateAllProducts(qc);
        invalidateDashboard(qc);
        notify("addison:bills-changed");
        toast.success(
          `🧾 Bill raised — ₹${d.totalAmount.toLocaleString("en-IN", { maximumFractionDigits: 0 })} · ${d.itemsCount} item${d.itemsCount !== 1 ? "s" : ""} · ${d.paymentMode.toUpperCase()}`,
          { duration: 4000 }
        );
      });

      /* ── payment recorded / return processed (both fire bill_payment) ── */
      es.addEventListener("bill_payment", () => {
        invalidateDashboard(qc);
        invalidateAllProducts(qc);   // returns restock, so product stock changed too
        notify("addison:bills-changed");
      });

      /* ── supplier created / paid ── */
      es.addEventListener("supplier_created",       () => notify("addison:suppliers-changed"));
      es.addEventListener("supplier_payment_added", () => notify("addison:suppliers-changed"));
      es.addEventListener("supplier_payment_deleted", () => notify("addison:suppliers-changed"));

      /* ── new product added ── */
      es.addEventListener("product_created", (e) => {
        const d = JSON.parse(e.data) as { name: string; sku: string };
        invalidateAllProducts(qc);
        invalidateDashboard(qc);
        toast.info(`🧸 New product — ${d.name} (${d.sku})`, { duration: 3000 });
      });

      /* ── product edited ── */
      es.addEventListener("product_updated", () => {
        invalidateAllProducts(qc);
        invalidateDashboard(qc);
      });

      /* ── shared cart updated (cross-device sync) ── */
      es.addEventListener("cart_updated", (e) => {
        const d = JSON.parse(e.data) as { items: CartItem[]; count: number; total: number; revision: number };
        syncRef.current(d.items, d.revision);
      });

      es.addEventListener("held_bills_updated", () => {
        void qc.invalidateQueries({ queryKey: ["held-bills"] });
      });

      /* ── low stock alert ── */
      es.addEventListener("low_stock_alert", (e) => {
        const d = JSON.parse(e.data) as {
          productName: string;
          stock:       number;
          threshold:   number;
        };
        toast.warning(
          `⚠️ Low stock: ${d.productName} — only ${d.stock} unit${d.stock !== 1 ? "s" : ""} left (threshold: ${d.threshold})`,
          { duration: 8000 }
        );
      });

      es.onerror = () => {
        es.close();
        ref.current = null;
        // Exponential back-off, cap at 30 s
        retryTimer = setTimeout(() => {
          retryDelay = Math.min(retryDelay * 1.5, 30_000);
          connect();
        }, retryDelay);
      };
    }

    connect();

    return () => {
      clearTimeout(retryTimer);
      ref.current?.close();
      ref.current = null;
    };
  }, [qc]);
}
